---
- hosts: network
  become: yes
  tasks:
    - name: backup frr daemons file
      fetch:
        dest=roles/{{ansible_hostname}}/daemons
        src=/etc/frr/daemons
        flat=yes

    - name: backup frr.conf
      fetch:
        dest=roles/{{ansible_hostname}}/frr.conf
        src=/etc/frr/frr.conf
        flat=yes
        
    - name: backup ports.conf
      fetch:
        dest=roles/{{ansible_hostname}}/ports.conf
        src=/etc/cumulus/ports.conf
        flat=yes

#    - name: backup traffic.conf
#      fetch:
#        dest=roles/{{ansible_hostname}}//etc/default/frr
#        src=/etc/cumulus/datapath/traffic.conf
#        flat=yes
        
     - name: backup frr settings
       fetch:
         dest=roles/{{ansible_hostname}}/frr
         src=/etc/default/frr
         flat=yes
       
     - name: backup COPP rules
       fetch:
         dest=roles/{{ansible_hostname}}/frr
         src=/etc/cumulus/acl/policy.d/00control_plane.rules
         flat=yes

# The following line is the method to copy a SINGLE interfaces file to the ansible server as
# a backup location. If using interfaces.d directory, use the next option in this file.

   - name: backup single interfaces file
     fetch:
       dest=roles/leafs/{{ansible_hostname}}/interfaces
       src=/etc/network/interfaces
       flat=yes

# The following line is a way to copy the entire /etc/network/interfaces.d directory into a backup location. 
# syncronize module would be preferred, but won't work with Vagrant for test environments.
# fetch module won't work as its only for copying single files, need to add the loop.
# syncronize option is listed and commented out

#    - name: List files in interfaces.d directory
#      shell: ls /etc/network/interfaces.d/
#      register: interfaces_files

#    - name: backup interfaces_files
#      fetch:
#        dest=roles/leafs/
#        src=/etc/network/interfaces.d/{{item}}
#      with_items: interfaces_files.stdout_lines
