---
# update apt sources list to enable EA features in Cumulus Linux
- hosts: network
  become: yes
  tasks:
  - name: configure apt sources.list - remove comments from EA repositories
    blockinfile:
      dest: /etc/apt/sources.list
      marker: "#"
      content: ""
  - name: Retrieve the updated package list
    apt: update_cache=yes
  - name: Install Network command line utility NCLU
    apt: name=nclu
  - name: Install cumulus-netq
    apt: name=cumulus-netq
  - name: Install OpenStack ML2 part 1
    apt: name=python-falcon
  - name: Install OpenStack ML2 part 2
    apt: name=python-cumulus-restapi
  - name: Install PIM Routing
    apt: name=cumulus-pim
  - name: Install TACACS+ client
    apt: name=tacplus-client
  - name: apt-get upgrade
    apt: upgrade=dist
