---
- name: reload networking
  shell: "service networking reload"
  register: networking_reload
  notify: print networking reload error
  changed_when: "networking_reload.stderr != ''"

- name: reload frr
  shell: "service frr reload"
  register: frr_reload
  notify: print frr reload error
  changed_when: "frr_reload.stderr != ''"

- name: print networking reload error
  debug: msg="{{networking_reload.stderr}}"
  when: networking_reload.stderr is defined
  failed_when: "networking_reload.stderr is defined"

- name: print frr reload error
  debug: msg="{{frr_reload.stderr}}"
  when: frr_reload.stderr is defined
  failed_when: "frr_reload.stderr is defined"

- name: restart apache
  service: name=apache2 state=restarted

- name: start clcmd_server
  service: name=clcmd_server state=started enabled=yes
  
- name: restart switchd
  service: name=switchd state=restarted
  
- name: restart frr
  service: name=frr state=restarted
  
- name: reload networking
  shell: "service networking reload"
  register: networking_reload
  notify: print networking reload error
  changed_when: "networking_reload.stderr != ''"
