---
   - name: fetch ports.conf
     fetch:
       dest=roles/leafs/{{ansible_hostname}}/ports.conf
       src=/etc/cumulus/ports.conf
       flat=yes

   - name: copy quagga daemons file
     fetch:
       dest=roles/leafs/{{ansible_hostname}}/daemons
       src=/etc/quagga/daemons
       flat=yes

   - name: copy Quagga.conf
     fetch:
       dest=roles/leafs/{{ansible_hostname}}/Quagga.conf
       src=/etc/quagga/Quagga.conf
       flat=yes

# The following line is the method to copy a SINGLE interfaces file to the ansible server as
# a backup location. If using interfaces.d directory, use the next option in this file.

#   - name: copy single interfaces file
#     fetch:
#       dest=roles/leafs/{{ansible_hostname}}/interfaces
#       src=/etc/network/interfaces
#       flat=yes

# The following line is a way to copy the entire /etc/network/interfaces.d directory into a backup location. 
# syncronize module would be preferred, but won't work with Vagrant for test environments.
# fetch module won't work as its only for copying single files, need to add the loop.
# syncronize option is listed and commented out

   - name: List files in interfaces.d directory
     shell: ls /etc/network/interfaces.d/
     register: interfaces_files

   - name: Fetch interfaces_files
     fetch:
       dest=roles/leafs/
       src=/etc/network/interfaces.d/{{item}}
     with_items: interfaces_files.stdout_lines

#    - name: Copy interfaces from the remote switch and save to local drive
#      synchronize: mode=pull src=/etc/network/interfaces.d dest=roles/leafs/{{ansible_hostname}}/interfaces.d
#        recursive=yes

# Change CLAGD priority to peer
   - name: Change CLAG priority to peer
     shell: sudo clagctl priority 65000

# Fetch current working NOS version
   - name: Show current Cumulus Linux version
     shell: cat /etc/lsb-release

# This step copies the new image to the switch

   - name: Fetch the latest update meta-data from the repository
     apt: update_cache=yes
   - name: Upgrade all the packages to the latest distribution
     apt: upgrade=dist
     
   - name: Waiting for leafs to restore. Please stand by...
     local_action:
       wait_for
       host={{ansible_ssh_host}}
       port={{ ansible_ssh_port }}
       delay=60
     become: False