---
# to run this playbook, use the following command:
# "ansible-playbook l2-troubleshooting-all.yml --verbose"
# 
# to run commands individually, use the following:
# ansible network -a "clagctl"
- hosts: network
  tasks:
    - name: Show MLAG
      command: sudo clagctl
 
    - name: Show Bridges
      command: sudo brctl show

    - name: Show Bridge MACs
      command: sudo brctl showmacs br0

    - name: Show Bridge STP
      command: sudo brctl showstp br0

    - name: Show links
      command: sudo ip link show

    - name: Show Interfaces
      command: sudo ifquery -a